FROM natansdj/php-orcl:72

# Install GIT LFS
RUN curl -s https://packagecloud.io/install/repositories/github/git-lfs/script.deb.sh | sudo bash \
    && apt-install git-lfs -y \
    && apt-get autoremove -y \
    && apt-get clean

# Configure volume/workdir
WORKDIR /app/
