FROM natansdj/php-orcl:71

# Install GIT LFS
RUN curl -s https://packagecloud.io/install/repositories/github/git-lfs/script.deb.sh | bash \
    && apt-install git-lfs -y \

    # Clean up APT when done.
    && apt-get autoremove -y \
    && apt-get clean
    && rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/*

# Configure volume/workdir
WORKDIR /app/
